### ISSUE TITLE
Flaky tests: event based storage

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#1664]
This will occasionally fail on CI

```
 panic: test timed out after 3m0s
 goroutine 54 [running]:
 testing.(*M).startAlarm.func1()
 	/usr/lib/go-1.13/src/testing/testing.go:1377 +0x11c
 created by time.goFunc
 	/usr/lib/go-1.13/src/time/sleep.go:168 +0x52
 goroutine 1 [chan receive]:
 testing.(*T).Run(0xc0000fe400, 0xc43308, 0x39, 0xc4d0c8, 0x1)
 	/usr/lib/go-1.13/src/testing/testing.go:961 +0x68a
 testing.runTests.func1(0xc0000fe400)
 	/usr/lib/go-1.13/src/testing/testing.go:1202 +0xa7
 testing.tRunner(0xc0000fe400, 0xc00018bcd8)
 	/usr/lib/go-1.13/src/testing/testing.go:909 +0x19a
 testing.runTests(0xc0000b7a80, 0x129c7e0, 0x1e, 0x1e, 0x0)
 	/usr/lib/go-1.13/src/testing/testing.go:1200 +0x522
 testing.(*M).Run(0xc0000fc300, 0x0)
 	/usr/lib/go-1.13/src/testing/testing.go:1117 +0x300
 main.main()
 	_testmain.go:180 +0x338
 goroutine 19 [chan receive]:
 github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000d04e0, 0xc0000d0420)
 	/home/gitlab-runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:36 +0xdf
 created by github.com/rjeczalik/notify.newNonrecursiveTree
 	/home/gitlab-runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:29 +0x1b9
 goroutine 20 [chan receive]:
 github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000d04e0, 0xc0000d0480)
 	/home/gitlab-runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:81 +0x69
 created by github.com/rjeczalik/notify.newNonrecursiveTree
 	/home/gitlab-runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:30 +0x1e5
 goroutine 52 [chan receive]:
 github.com/mysteriumnetwork/node/session.TestEventBasedStorage_PublishesEventsOnDataTransferUpdate(0xc0001d8000)
 	/home/gitlab-runner/go/src/github.com/mysteriumnetwork/node/session/event_based_storage_test.go:98 +0x2f9
 testing.tRunner(0xc0001d8000, 0xc4d0c8)
 	/usr/lib/go-1.13/src/testing/testing.go:909 +0x19a
 created by testing.(*T).Run
 	/usr/lib/go-1.13/src/testing/testing.go:960 +0x652

```

**Comment by vkuznecovas** [comment]
/usr/local/bin/go test -timeout 30s github.com/mysteriumnetwork/node/session -count=1000 -run TestNewEventBasedStorage_HandlesAppEventTokensEarned

This still fails.
