### ISSUE TITLE
Flaky test: p2p dialer test

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#1981]
```
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 42276"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 44808"}
{"level":"error","error":"I don't like you","time":"2020-04-01T12:41:00+03:00","message":"Handler \"get-error\" public error"}
{"level":"error","error":"I don't like you","time":"2020-04-01T12:41:00+03:00","message":"Handler \"get-error\" internal error"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 49950"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 48554"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Consumer 0x91cc021e919463329f27fb7d17f6d0286fb0c0ca sending public key 7101a620205a15585f39d4181220320f164f6712af17f068df960622f1e07f00 to provider 0x63f05a797ab55f346eab797eec62d3a252537b01"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Received consumer public key 7101a620205a15585f39d4181220320f164f6712af17f068df960622f1e07f00"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 47739"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 42617"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 40616"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 41218"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 42901"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 41691"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 48870"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 49814"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 43911"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 45439"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 43481"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 49496"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 46866"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 46590"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 41044"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 40358"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 48283"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 48628"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 45340"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 47880"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Sending reply with public key e541a0cbf84252e71bf687e46a59b4a0807462dc005c321627a8296a32d4862a and encrypted config to consumer"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Consumer 0x91cc021e919463329f27fb7d17f6d0286fb0c0ca received provider 0x63f05a797ab55f346eab797eec62d3a252537b01 with config: publicIP:\"127.0.0.1\" ports:47739 ports:42617 ports:40616 ports:41218 ports:42901 ports:41691 ports:48870 ports:49814 ports:43911 ports:45439 ports:43481 ports:49496 ports:46866 ports:46590 ports:41044 ports:40358 ports:48283 ports:48628 ports:45340 ports:47880"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 43583"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 47447"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 43622"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 43775"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 48418"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 41843"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 49458"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 42319"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 49204"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 42012"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 48706"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 47492"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 43784"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 42188"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 49780"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 41999"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 48694"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 41379"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 43475"}
{"level":"info","time":"2020-04-01T12:41:00+03:00","message":"Supplying port 41995"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Consumer 0x91cc021e919463329f27fb7d17f6d0286fb0c0ca sending ack with encrypted config to provider 0x63f05a797ab55f346eab797eec62d3a252537b01"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Decrypted consumer config: publicIP:\"127.0.0.1\" ports:43583 ports:47447 ports:43622 ports:43775 ports:48418 ports:41843 ports:49458 ports:42319 ports:49204 ports:42012 ports:48706 ports:47492 ports:43784 ports:42188 ports:49780 ports:41999 ports:48694 ports:41379 ports:43475 ports:41995"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Pinging consumer with IP 127.0.0.1 using ports [47739 42617 40616 41218 42901 41691 48870 49814 43911 45439 43481 49496 46866 46590 41044 40358 48283 48628 45340 47880]:[43583 47447 43622 43775 48418 41843 49458 42319 49204 42012 48706 47492 43784 42188 49780 41999 48694 41379 43475 41995]"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Will use service conn with local port: 48554, remote port: 49950"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Creating channel with listen port: 48554, peer port: 49950"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Pinging provider 0x63f05a797ab55f346eab797eec62d3a252537b01 with IP 127.0.0.1 using ports [43583 47447 43622 43775 48418 41843 49458 42319 49204 42012 48706 47492 43784 42188 49780 41999 48694 41379 43475 41995]:[47739 42617 40616 41218 42901 41691 48870 49814 43911 45439 43481 49496 46866 46590 41044 40358 48283 48628 45340 47880]"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Will use service conn with local port: 49950, remote port: 48554"}
{"level":"debug","time":"2020-04-01T12:41:00+03:00","message":"Creating channel with listen port: 49950, peer port: 48554"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49a3dd4]

goroutine 150 [running]:
testing.tRunner.func1(0xc0003fe200)
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:874 +0x69f
panic(0x4aad920, 0x523dd70)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
github.com/mysteriumnetwork/node/p2p.TestDialerExchangeAndCommunication.func3(0xc0003fe200)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/p2p/dialer_test.go:85 +0x444
testing.tRunner(0xc0003fe200, 0xc000360420)
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:960 +0x652
FAIL	github.com/mysteriumnetwork/node/p2p	0.338s
```

**Comment by anjmao** [comment]
Should be fixed with https://github.com/mysteriumnetwork/node/pull/1986
