### ISSUE TITLE
[android, 0.31.0-rc2] nodeRepository.getIdentity throws exception or crashes app

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2093]
This didn't occur (ever) in node 0.22.5.

In node: 0.31.0-rc2, when calling nodeRepository.getIdentity(), it either crashes the app (without much errors), throws exception, and occasionally - works fine.

If I get exception, and try again in few seconds - it works fine (so it seems it's just when attempting for the first time).

1) When app crashed, got only the following:
E/GoLog: [90m2020-04-20T14:36:37.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/selector/handler.go:62[0m[36m >[0m Creating new identity
E/GoLog: [90m2020-04-20T14:36:37.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/selector/handler.go:118[0m[36m >[0m Attempting to use new identity
 E/GoLog: [90m2020-04-20T14:36:42.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/eventbus/event_bus.go:81[0m[36m >[0m Published topic="identity-created" event=0x27d46da2c8ec179d0689e08914fab74ffcaaf881

2) When app wasn't crashed, I got exception:

    go.Universe$proxyerror: could not unlock identity: failed to register identity: server response invalid: 403 FORBIDDEN (https://testnet-api.mysterium.network/v1/identities){"error":"identity already exists"}
    
        at mysterium.MobileNode.getIdentity(Native Method)
        at network.portals.service.core.NodeRepository$getIdentity$2.invokeSuspend(NodeRepository.kt:156)
        at network.portals.service.core.NodeRepository$getIdentity$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:156)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at network.portals.service.core.NodeRepository.getIdentity(NodeRepository.kt:156)
        ..
E/GoLog: [90m2020-04-20T14:42:56.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/eventbus/event_bus.go:81[0m[36m >[0m Published topic="transactor_identity_registration" event={RegistryAddress:0x3dD81545F3149538EdCb6691A4FfEE1898Bd2ef0 AccountantID:0x0214281cf15C1a66b51990e2E65e1f7b7C363318 Stake:0 Fee:10000000 Beneficiary:0x1eb15e33aa8e4c386d7c5cb6ea5169d3608603b1 Signature:0x929d982e657ebe60e2d3671d80ab27adfb116452a6e83a8ccd02ea068730e8440ee81aa8a5fd791c4a92d7eaed95bf9af3eeec1060e8f3a9f9be6595b66695a11c Identity:0xb69629f6bc131c52b4f0818442d6b33fc31a9dcc}
E/GoLog: [90m2020-04-20T14:42:56.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/eventbus/event_bus.go:81[0m[36m >[0m Published topic="registration_event_topic" event={ID:{Address:0xb69629f6bc131c52b4f0818442d6b33fc31a9dcc} Status:InProgress}
E/GoLog: [90m2020-04-20T14:42:56.000[0m [32mINF[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/registry/registry_contract.go:203[0m[36m >[0m Waiting on identities 0xb69629F6bC131c52B4f0818442d6B33FC31A9Dcc accountant 0x0214281cf15C1a66b51990e2E65e1f7b7C363318

This occurs both in emulator and in phone.

**Comment by anjmao** [comment]
Hi. This looks strange. I suspect you got second error because of the first one. As your app crashed during identity creation (but looks that it managed to call discovery api and register identity in DB). That would explain `(https://testnet-api.mysterium.network/v1/identities){"error":"identity already exists"}` error. 

I'm checking why app could have crashed in this case.

**Comment by anjmao** [comment]
@cvl I cannot reproduce. Tried on both simulator and real device to create new identities multiple times, but seems to work.

**Comment by cvl** [comment]
Here's how to reproduce on MysteriumVPN app:

1) Pass nodeRepository to TermsViewModel constructor:
class TermsViewModel(private val appDatabase: AppDatabase, private val nodeRepository: NodeRepository): ViewModel() {

2) Change acceptCurrentTerms to:

suspend fun acceptCurrentTerms() {

        Log.i("xxx", "getting identity _________")
        val identity:Identity = nodeRepository.getIdentity()

        val channelAddress:String? = identity.channelAddress
        val mid:String? = identity.address

        Log.i("xxx", "identity: ${mid} channel: ${channelAddress}")
//        appDatabase.termsDao().delete()
//        appDatabase.termsDao().insert(Terms(termsVersion))
    }

3) You may also want to comment out navigating to vpn_screen for clarity sake in TermsFragment onclick listener.

4) Run app in emulator.

What I get is the following:

2020-04-22 10:29:43.442 22433-22433/network.mysterium.vpn I/xxx: getting identity _________
2020-04-22 10:29:43.473 22433-22548/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:43.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/eventbus/event_bus.go:81[0m[36m >[0m Published topic="identity-created" event=0x3f24dba7f5b34dd578fb715a4427ace77c30bc60
2020-04-22 10:29:43.474 22433-22554/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:43.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/selector/handler.go:102[0m[36m >[0m Attempting to use last identity
2020-04-22 10:29:43.477 22433-22548/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:43.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/selector/handler.go:68[0m[36m >[0m Using existing identity
2020-04-22 10:29:43.484 22433-22548/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:43.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/selector/handler.go:76[0m[36m >[0m Attempting to use existing identity
2020-04-22 10:29:43.489 22433-22433/network.mysterium.vpn I/Choreographer: Skipped 59 frames!  The application may be doing too much work on its main thread.
2020-04-22 10:29:43.584 22433-22517/network.mysterium.vpn I/OpenGLRenderer: Davey! duration=1082ms; Flags=0, IntendedVsync=3993394993579, Vsync=3994378326873, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=3994386102050, AnimationStart=3994386324050, PerformTraversalsStart=3994424389050, DrawStart=3994435511050, SyncQueued=3994471961050, SyncStart=3994472073050, IssueDrawCommandsStart=3994472127050, SwapBuffers=3994475551050, FrameCompleted=3994478079050, DequeueBufferDuration=419000, QueueBufferDuration=1357000, 
2020-04-22 10:29:51.401 22433-22558/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:51.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/manager.go:142[0m[36m >[0m Caching unlocked address: 0x3f24dba7f5b34dd578fb715a4427ace77c30bc60
2020-04-22 10:29:51.507 22433-22558/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:51.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/eventbus/event_bus.go:81[0m[36m >[0m Published topic="identity-unlocked" event=0x3f24dba7f5b34dd578fb715a4427ace77c30bc60
2020-04-22 10:29:51.508 22433-22558/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:51.000[0m [33mDBG[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/manager.go:129[0m[36m >[0m Unlocked identity found in cache, skipping keystore: 0x3f24dba7f5b34dd578fb715a4427ace77c30bc60
2020-04-22 10:29:51.949 22433-22579/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:51.000[0m [32mINF[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/market/mysterium/mysterium_api.go:79[0m[36m >[0m Identity registered: 0x3f24dba7f5b34dd578fb715a4427ace77c30bc60
2020-04-22 10:29:51.951 22433-22579/network.mysterium.vpn E/GoLog: [90m2020-04-22T07:29:51.000[0m [32mINF[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/identity/selector/handler.go:91[0m[36m >[0m Existing identity is not registered, attempting to register
2020-04-22 10:29:52.254 22433-22433/network.mysterium.vpn I/AccountViewModel: Loaded identity 0x3f24dba7f5b34dd578fb715a4427ace77c30bc60, channel addr: 0x4E655aAf80827E05ef9b0170b4eA35Ba617D2f5d
2020-04-22 10:29:54.743 22433-22433/network.mysterium.vpn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: network.mysterium.vpn, PID: 22433
    go.Universe$proxyerror: could not unlock identity: failed to register identity: server response invalid: 403 FORBIDDEN (https://testnet-api.mysterium.network/v1/identities){"error":"identity already exists"}
    
        at mysterium.MobileNode.getIdentity(Native Method)
        at network.mysterium.service.core.NodeRepository$getIdentity$2.invokeSuspend(NodeRepository.kt:152)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
2020-04-22 10:29:59.160 22433-22433/network.mysterium.vpn I/Process: Sending signal. PID: 22433 SIG: 9



So it behaves really weird, as it clearly gets the identity (channel and identity addresses are being printed out), yet it still throws exception (I guess in a separate thread).

**Comment by anjmao** [comment]
Check this method https://github.com/mysteriumnetwork/mysterium-vpn-mobile/blob/master/android/app/src/main/java/network/mysterium/ui/AccountViewModel.kt#L105
On app startup it will try to automatically register identity into python discovery here https://github.com/mysteriumnetwork/node/blob/master/identity/selector/handler.go#L91

So the problem is that you call nodeRepository.getIdentity twice while it's not registered. I can add lock for GetIdentity method which should solve this problem.

**Comment by cvl** [comment]
Works very well, thank you!
