### ISSUE TITLE
Python discovery promo HTTP timeout

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2121]
Sometimes getting such error on python discovery
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f9ff454f9e8>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='victoriametrics.mysterium.network', port=443): Max retries exceeded with url: /api/v1/query?query=ALERTS%7Balertname%3D%22provider_down%22%2C+alertstate%3D%22firing%22%7D&time=1587965711.000736 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9ff454f9e8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/api/node_monitoring_worker.py", line 25, in process_node_monitoring
    data = json.loads(prometheus.query(metric='ALERTS{alertname="provider_down", alertstate="firing"}'))
  File "/usr/local/lib/python3.6/site-packages/prometheus_http_client/provider/core.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/prometheus_http_client/provider/__init__.py", line 42, in _q
    headers=self.headers).text
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='victoriametrics.mysterium.network', port=443): Max retries exceeded with url: /api/v1/query?query=ALERTS%7Balertname%3D%22provider_down%22%2C+alertstate%3D%22firing%22%7D&time=1587965711.000736 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9ff454f9e8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by soffokl** [comment]
There are some problems with accessing hetzner hosts from outside world. This is probably related to it.

**Comment by anjmao** [comment]
Thanks, yes it could be. Do we have any plans to move other services to hetzner too or are there some issues?
