### ISSUE TITLE
Panic on service session Close on provider

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#2778]
```
2020-10-27T16:29:28.123 DBG core/service/session_manager.go:172      > Provider connection trace: "Provider whole Connect" took 31.293511231s, "Provider P2P exchange" took 534.631283ms, "Provider P2P exchange (ports)" took 529.321717ms, "Provider P2P exchange ack" took 60.641649ms, "Provider P2P dial (pinger)" took 654.072447ms, "Provider P2P dial ack" took 9.949515ms, "Provider session create" took 30.007863016s, "Provider session create (start)" took 5.540244ms, "Provider session create (payment)" took 30.002308466s
2020-10-27T16:29:28.123 ERR core/service/session_manager.go:163      > Session failed, disconnecting error="first invoice was not paid: failed waiting for first invoice"
2020-10-27T16:29:28.125 DBG session/pingpong/invoice_tracker.go:600  > Stopping...
2020-10-27T16:29:28.125 ERR p2p/channel.go:408                       > Handler "p2p-session-create" internal error error="cannot start session: : first invoice was not paid: failed waiting for first invoice"
2020-10-27T16:29:28.129 WRN github.com/mysteriumnetwork/payments@v0.0.14-0.20200930122451-4dab72dcce06/client/retryable_client.go:103 > retry 2 of 3 error="could not get hermes fee: could not get hermes fee: context deadline exceeded"
2020-10-27T16:29:28.131 DBG consumer/session/session_storage.go:293  > Session 726e22a8-f785-4236-ac35-11628a9a83f4 updated with final data
2020-10-27T16:29:31.120 ERR core/service/session_manager.go:344      > Failed to send p2p keepalive ping. SessionID=726e22a8-f785-4236-ac35-11628a9a83f4 error="timeout waiting for reply to \"p2p-keepalive\": p2p send timeout"
2020-10-27T16:29:58.441 WRN github.com/mysteriumnetwork/payments@v0.0.14-0.20200930122451-4dab72dcce06/client/retryable_client.go:103 > retry 3 of 3 error="could not get hermes fee: could not get hermes fee: context deadline exceeded"
2020-10-27T16:30:28.750 ERR core/service/session_manager.go:280      > Payment engine error error="could not get hermess fee: could not get hermes fee: could not get hermes fee: context deadline exceeded"
panic: close of closed channel

goroutine 66535 [running]:
github.com/mysteriumnetwork/node/core/service.(*Session).Close(0xc0004d2300)
	/go/src/github.com/mysteriumnetwork/node/core/service/session.go:53 +0x47
github.com/mysteriumnetwork/node/core/service.(*SessionManager).paymentLoop.func2(0x1df4000, 0xc000bb6a80, 0xc0004d2300)
	/go/src/github.com/mysteriumnetwork/node/core/service/session_manager.go:281 +0xb1
created by github.com/mysteriumnetwork/node/core/service.(*SessionManager).paymentLoop
	/go/src/github.com/mysteriumnetwork/node/core/service/session_manager.go:277 +0x23a

**Comment by vkuznecovas** [comment]
This has been solved by cd6844405c45f2f310aedb17ff72b3cbdc680843
