### ISSUE TITLE
Can't connect to any provider (old problem comes back?)

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3072]
node: 0.41.5

This will be hard to reproduce, but perhaps something can be seen in logs. Similar problem occurred few months ago.

Renderer logs:

[2021-01-29 11:54:59.517] [info] Daemon is starting, skipping healthcheck
[2021-01-29 11:55:01.521] [info] Daemon is starting, skipping healthcheck
[2021-01-29 16:29:37.036] [error] Failed to connect to the supervisor, installing connect ECONNREFUSED /var/run/myst.sock
[2021-01-29 16:30:43.839] [info] Daemon is starting, skipping healthcheck
[2021-01-29 16:33:13.953] [error] Could not connect Request failed with status code 500 (path="connection")
[2021-01-29 16:33:17.766] [error] Could not connect Request failed with status code 500 (path="connection")
[2021-01-29 16:33:20.206] [error] Could not connect Request failed with status code 500 (path="connection")
[2021-01-29 16:33:20.237] [error] Could not connect Request failed with status code 500 (path="connection")
[2021-01-29 16:33:23.136] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:23.639] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:24.102] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:24.500] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:24.932] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:25.434] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:25.864] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:26.310] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:26.768] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:27.389] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:27.978] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:34.361] [error] Could not connect Request failed with status code 500 (path="connection")
[2021-01-29 16:33:34.980] [error] Could not connect Request failed with status code 500 (path="connection")
[2021-01-29 16:33:35.654] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:35.728] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:36.114] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:36.193] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:36.508] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:36.620] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:36.939] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:37.052] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:37.354] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:37.442] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:37.747] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:37.849] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:38.030] xxxx
[2021-01-29 16:33:38.051] xxxx
[2021-01-29 16:33:38.115] xxxx
[2021-01-29 16:33:38.227] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:38.284] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:38.310] xxxx
[2021-01-29 16:33:38.398] xxxx
[2021-01-29 16:33:38.446] xxxx
[2021-01-29 16:33:38.581] xxxx
[2021-01-29 16:33:38.582] xxxx
[2021-01-29 16:33:38.641] xxxx
[2021-01-29 16:33:38.642] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:38.646] xxxx
[2021-01-29 16:33:38.669] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:39.062] xxxx
[2021-01-29 16:33:39.065] xxxx
[2021-01-29 16:33:39.066] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:39.067] xxxx
[2021-01-29 16:33:39.068] xxxx
[2021-01-29 16:33:39.068] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:39.464] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:39.512] xxxx
[2021-01-29 16:33:39.513] xxxx
[2021-01-29 16:33:39.513] xxxx
[2021-01-29 16:33:39.514] xxxx
[2021-01-29 16:33:39.544] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:39.797] xxxx
[2021-01-29 16:33:39.801] xxxx
[2021-01-29 16:33:39.857] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:39.943] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:40.113] xxxx
[2021-01-29 16:33:40.148] xxxx
[2021-01-29 16:33:40.258] xxxx
[2021-01-29 16:33:40.259] xxxx
[2021-01-29 16:33:40.261] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:40.317] xxxx
[2021-01-29 16:33:40.321] xxxx
[2021-01-29 16:33:40.344] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:40.622] xxxx
[2021-01-29 16:33:40.645] xxxx
[2021-01-29 16:33:40.682] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:40.723] xxxx
[2021-01-29 16:33:40.827] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:40.903] xxxx
[2021-01-29 16:33:41.032] xxxx
[2021-01-29 16:33:41.053] xxxx
[2021-01-29 16:33:41.072] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:41.176] xxxx
[2021-01-29 16:33:41.181] xxxx
[2021-01-29 16:33:41.240] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:41.461] xxxx
[2021-01-29 16:33:41.475] xxxx
[2021-01-29 16:33:41.547] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:41.615] xxxx
[2021-01-29 16:33:41.619] xxxx
[2021-01-29 16:33:41.663] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:41.891] xxxx
[2021-01-29 16:33:41.892] xxxx
[2021-01-29 16:33:41.947] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:42.028] xxxx
[2021-01-29 16:33:42.036] xxxx
[2021-01-29 16:33:42.118] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:42.313] xxxx
[2021-01-29 16:33:42.315] xxxx
[2021-01-29 16:33:42.359] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:42.471] xxxx
[2021-01-29 16:33:42.503] xxxx
[2021-01-29 16:33:42.555] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:42.742] xxxx
[2021-01-29 16:33:42.766] xxxx
[2021-01-29 16:33:42.783] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:42.946] xxxx
[2021-01-29 16:33:42.948] xxxx
[2021-01-29 16:33:42.975] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:43.153] xxxx
[2021-01-29 16:33:43.154] xxxx
[2021-01-29 16:33:43.198] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:43.328] xxxx
[2021-01-29 16:33:43.332] xxxx
[2021-01-29 16:33:43.543] xxxx
[2021-01-29 16:33:43.553] xxxx
[2021-01-29 16:33:51.979] [error] TequilapiError: timeout of 5000ms exceeded (path="proposals")
    at new TequilapiError (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/tequilapi-error.js:36:28)
    at /Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/http/axios-adapter.js:61:27
    at step (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/http/axios-adapter.js:39:23)
    at Object.throw (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/http/axios-adapter.js:20:53)
    at rejected (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/http/axios-adapter.js:12:65)
[2021-01-29 16:33:54.529] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:54.531] [error] Could not connect Request failed with status code 409 (path="connection")
[2021-01-29 16:33:57.332] [error] TequilapiError: Request failed with status code 500 (path="proposals")
    at new TequilapiError (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/tequilapi-error.js:36:28)
    at /Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/http/axios-adapter.js:61:27
    at step (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/http/axios-adapter.js:39:23)
    at Object.throw (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/http/axios-adapter.js:20:53)
    at rejected (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/mysterium-vpn-js/lib/http/axios-adapter.js:12:65)
[2021-01-29 16:33:59.500] xxxx

Myst logs attached.
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/5897756/mysterium-node.log)

**Comment by chompomonim** [comment]
@cvl please add new logs when this repeats. Also if you would mention app and node version, this also would help.

We tried to investigate this issue but were not able to reproduce it :/

**Comment by cvl** [comment]
Doesn't recur anymore, will reopen if repeats.
