### ISSUE TITLE
[macos, bug] app fails to install supervisor

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3127]
[2021-02-20 14:31:16.868] [error] Failed to connect to the supervisor, installing connect ECONNREFUSED /var/run/myst.sock
[2021-02-20 14:31:16.899] [error] Failed to install supervisor ReferenceError: window is not defined
    at MatomoTracker.track (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/@datapunt/matomo-tracker-js/src/MatomoTracker.ts:297:21)
    at MatomoTracker.trackEvent (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/node_modules/@datapunt/matomo-tracker-js/src/MatomoTracker.ts:182:12)
    at analytics_event (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/webpack:/src/analytics/analytics.ts:51:13)
    at appStateEvent (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/webpack:/src/analytics/analytics.ts:59:5)
    at supervisor_Supervisor.install (/Applications/MysteriumVPN.app/Contents/Resources/app.asar/webpack:/src/supervisor/supervisor.ts:162:9)
    at electron/js2c/browser_init.js:213:8594
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4973)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:483:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9577)

**Comment by tomasmik** [comment]
Please provide additional information starting with the app version and if this was a fresh/clean install. Any other information which may help is also appreciated.

**Comment by cvl** [comment]
Fresh install, version 3.6.0.
Tried restarting computer - didn't help.

**Comment by tadaskay** [comment]
@cvl https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/3.7.0
