### ISSUE TITLE
[android] Can't run in dev mode

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3488]
**Describe the bug**
Trying to run https://github.com/mysteriumnetwork/mysterium-vpn-mobile

Getting the following:
I/ResourcesCompat: Failed to retrieve rebase() method
    java.lang.NoSuchMethodException: rebase []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at androidx.core.content.res.ResourcesCompat$ThemeCompat$ImplApi23.rebase(ResourcesCompat.java:501)
        at androidx.core.content.res.ResourcesCompat$ThemeCompat.rebase(ResourcesCompat.java:477)
        at androidx.appcompat.app.AppCompatDelegateImpl.attachBaseContext2(AppCompatDelegateImpl.java:465)
        at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:107)
        at updated.mysterium.vpn.ui.base.BaseActivity.attachBaseContext(BaseActivity.kt:46)
        at android.app.Activity.attach(Activity.java:7051)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2873)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by cvl** [comment]
This error is on API 28.
On API 29 there are no errors, but the app doesn't boot up, it's just a purple screen without any visuals.

<img width="554" alt="Screenshot 2021-06-15 at 13 23 06" src="https://user-images.githubusercontent.com/100252/122037124-f6ad8c00-cddc-11eb-8b73-c8a329fb1303.png">

**Comment by mdomasevicius** [comment]
@cvl this seems to be a bug or misuse of android API

either way the problem is here:

```kotlin
    private fun checkForGoogleMarketUpdates(afterAction: () -> Unit) {
        appUpdateManager.appUpdateInfo.addOnSuccessListener { appUpdateInfo ->
            if (appUpdateInfo.updateAvailability() == UpdateAvailability.UPDATE_AVAILABLE &&
                appUpdateInfo.isUpdateTypeAllowed(AppUpdateType.IMMEDIATE)
            ) {
                showNewVersionAvailablePopUp()
            } else {
                afterAction.invoke()
            }
        }
    }
```

the `afterAction.invoke()` is never called, because the listener is never notified (it seems). 
Current workaround (for development on emulator):

```kotlin
    private fun checkForGoogleMarketUpdates(afterAction: () -> Unit) {
/*        appUpdateManager.appUpdateInfo.addOnSuccessListener { appUpdateInfo ->
            if (appUpdateInfo.updateAvailability() == UpdateAvailability.UPDATE_AVAILABLE &&
                appUpdateInfo.isUpdateTypeAllowed(AppUpdateType.IMMEDIATE)
            ) {
                showNewVersionAvailablePopUp()
            } else {
                afterAction.invoke()
            }
        }*/
        afterAction.invoke()
    }
```

**Comment by cvl** [comment]
Thank you, this helped!
