### ISSUE TITLE
Node panics if you try to connect to a proposal that doesn't exist

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#3524]
```
goroutine 401 [running]:
net/http.(*conn).serve.func1(0xc000732000)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x135d740, 0x2393060)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/mysteriumnetwork/node/core/discovery.(*PricedServiceProposalRepository).Proposal(0xc0001a7580, 0xc0009c00a0, 0x4, 0xc000a20900, 0x32, 0x0, 0x0, 0x4, 0x0)
	/home/tomas/go/src/github.com/mysteriumnetwork/node/core/discovery/priced_repository.go:52 +0xdc
github.com/mysteriumnetwork/node/tequilapi/endpoints.(*ConnectionEndpoint).Create(0xc000a82540, 0x1be4bb0, 0xc000f92540, 0xc00022b200, 0x0, 0x0, 0x0)
	/home/tomas/go/src/github.com/mysteriumnetwork/node/tequilapi/endpoints/connection.go:193 +0x10e8
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000def2c0, 0x1be4bb0, 0xc000f92540, 0xc00022b200)
	/home/tomas/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0xb70
github.com/mysteriumnetwork/node/tequilapi.corsHandler.ServeHTTP(0x1bc8900, 0xc000def2c0, 0x1bcb620, 0xc000aa86c0, 0x1be4bb0, 0xc000f92540, 0xc00022b200)
	/home/tomas/go/src/github.com/mysteriumnetwork/node/tequilapi/http_middlewares.go:42 +0xde
github.com/mysteriumnetwork/node/tequilapi.cacheControl.ServeHTTP(0x1bcb640, 0xc000841520, 0x1be4bb0, 0xc000f92540, 0xc00022b200)
	/home/tomas/go/src/github.com/mysteriumnetwork/node/tequilapi/http_middlewares.go:84 +0x1f4
net/http.serverHandler.ServeHTTP(0xc000d82000, 0x1be4bb0, 0xc000f92540, 0xc00022b200)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000732000, 0x1be9740, 0xc000b7a240)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by vkuznecovas** [comment]
49d554516e4c0ed70035a395c28d3f2ff6c947f1 fixes this.
