### ISSUE TITLE
Can't upgrade to testnet3

### ISSUE THREAD

**Issue by masterdot** [mysteriumnetwork/node#3720]
`sudo add-apt-repository ppa:mysteriumnetwork/testnet3             Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster`

Error adding the ppa. My raspbian is a focal. I did change the ppa in /etc/apt/sources.list.d/mysterium.list
But it didn't work either.

I imported the key for the ppa, says its unchanged.

Any idea?

**Comment by masterdot** [comment]
I don't know why, but it did update now.
It's running now 0.53.0-1branch-testnet3-b-1
