### ISSUE TITLE
 panic: runtime error

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4009]
**Describe the bug**
After update to 0.66.1 node becomes unresponsive.
0x00f735d4ad380b56b92cd6c9f078763bbfeab3e8

```
Sep 29 04:34:57 rokas myst[267344]: 2021-09-29T04:34:57.673 INF services/wireguard/service/service_unix.go:254 > Wireguard: starting
Sep 29 04:34:57 rokas myst[267344]: 2021-09-29T04:34:57.673 DBG core/ip/cached_resolver.go:55            > Found cached outbound IP
Sep 29 04:34:57 rokas myst[267344]: 2021-09-29T04:34:57.674 INF dns/proxy.go:53                          > Starting DNS proxy on: :11253
Sep 29 04:34:57 rokas myst[267344]: 2021-09-29T04:34:57.674 INF services/wireguard/service/service_unix.go:285 > Wireguard: started
Sep 29 04:34:57 rokas myst[267344]: 2021-09-29T04:34:57.675 DBG config/config.go:220                     > Returning user config value mmn.api-key:0HeOP7t8WmjK5zLewRKY69nSqdfdjtvozKr6N4peFLV
Sep 29 04:34:57 rokas myst[267344]: 2021-09-29T04:34:57.678 DBG config/config.go:224                     > Returning default value launcher.ver:
Sep 29 04:34:57 rokas myst[267344]: panic: runtime error: index out of range [1] with length 1
Sep 29 04:34:57 rokas myst[267344]: goroutine 375 [running]:
Sep 29 04:34:57 rokas myst[267344]: github.com/mysteriumnetwork/node/mmn.(*MMN).register(0xc00099bd40, 0x18133e1, 0xb)
Sep 29 04:34:57 rokas myst[267344]:         /build/myst-cyRHkv/myst-0.66.1+build379017036+focal/go/src/github.com/mysteriumnetwork/node/mmn/mmn.go:104 +0x643
Sep 29 04:34:57 rokas myst[267344]: github.com/mysteriumnetwork/node/mmn.(*MMN).handleServiceStart(0xc00099bd40, 0xc00075c960, 0x24, 0xc000dd2090, 0x2a, 0xc00068b630, 0x9, 0x180c7da, 0x7)
Sep 29 04:34:57 rokas myst[267344]:         /build/myst-cyRHkv/myst-0.66.1+build379017036+focal/go/src/github.com/mysteriumnetwork/node/mmn/mmn.go:94 +0x96
Sep 29 04:34:57 rokas myst[267344]: reflect.Value.call(0x15232c0, 0xc00052b6a0, 0x13, 0x1808738, 0x4, 0xc00091cde0, 0x1, 0x1, 0x0, 0x16d6200, ...)
Sep 29 04:34:57 rokas myst[267344]:         /usr/lib/go-1.13/src/reflect/value.go:460 +0x5f6
Sep 29 04:34:57 rokas myst[267344]: reflect.Value.Call(0x15232c0, 0xc00052b6a0, 0x13, 0xc00091cde0, 0x1, 0x1, 0xc00091cde0, 0x1, 0x1)
Sep 29 04:34:57 rokas myst[267344]:         /usr/lib/go-1.13/src/reflect/value.go:321 +0xb4
Sep 29 04:34:57 rokas myst[267344]: github.com/mysteriumnetwork/node/vendor/github.com/asaskevich/EventBus.(*EventBus).doPublish(0xc000784ec0, 0xc0003f16b0, 0x1817201, 0xe, 0xc000a0b860, 0x1, 0x1)
Sep 29 04:34:57 rokas myst[267344]:         /build/myst-cyRHkv/myst-0.66.1+build379017036+focal/go/src/github.com/mysteriumnetwork/node/vendor/github.com/asaskevich/EventBus/event_bus.go:158 +0xa8
Sep 29 04:34:57 rokas myst[267344]: github.com/mysteriumnetwork/node/vendor/github.com/asaskevich/EventBus.(*EventBus).doPublishAsync(0xc000784ec0, 0xc0003f16b0, 0x1817201, 0xe, 0xc000a0b860, 0x1, 0x1)
Sep 29 04:34:57 rokas myst[267344]:         /build/myst-cyRHkv/myst-0.66.1+build379017036+focal/go/src/github.com/mysteriumnetwork/node/vendor/github.com/asaskevich/EventBus/event_bus.go:166 +0xd7
Sep 29 04:34:57 rokas myst[267344]: created by github.com/mysteriumnetwork/node/vendor/github.com/asaskevich/EventBus.(*EventBus).Publish
Sep 29 04:34:57 rokas myst[267344]:         /build/myst-cyRHkv/myst-0.66.1+build379017036+focal/go/src/github.com/mysteriumnetwork/node/vendor/github.com/asaskevich/EventBus/event_bus.go:150 +0x25b
Sep 29 04:34:57 rokas systemd[1]: mysterium-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 29 04:34:57 rokas systemd[1]: mysterium-node.service: Failed with result 'exit-code'.
```

**Comment by tomasmik** [comment]
Fixed in: https://github.com/mysteriumnetwork/node/pull/4011/files
