### ISSUE TITLE
Raspberry Pi 4 - GNU/Linux Debian 11 - identities beneficiary-status returns "panic: runtime error: index out of range [0] with length 0"

### ISSUE THREAD

**Issue by blackmennewstyle** [mysteriumnetwork/node#5338]
Hello,

I installed mysteriumnetwork **Branch: 1.9.2. Build id: 570175622. Commit: a5cea4f0** on my **Raspberry Pi 4 8GB** running **GNU/Linux Debian 11** with kernel **5.10.0-16-arm64**.
I get the following error when i run the following command `identities beneficiary-status 0x************************`
```
identities beneficiary-status 0x************************
[INFO] Current beneficiary: 0x*************************
[INFO] Is a channel address: false
[ERROR] panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/mysteriumnetwork/node/cmd/commands/cli/clio.sentenceCase(...)
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/cmd/commands/cli/clio/clio.go:75
github.com/mysteriumnetwork/node/cmd/commands/cli/clio.Error({0x4000771988, 0x1, 0x1})
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/cmd/commands/cli/clio/clio.go:63 +0x158
github.com/mysteriumnetwork/node/cmd/commands/cli.(*cliApp).handleActions(0x40001e0360, {0x40000300c0, 0x3, 0x4})
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/cmd/commands/cli/command.go:276 +0x5b4
github.com/mysteriumnetwork/node/cmd/commands/cli.(*cliApp).Run(0x40001e0360, 0x4000219140)
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/cmd/commands/cli/command.go:211 +0x3e8
github.com/mysteriumnetwork/node/cmd/commands/cli.NewCommand.func1(0x40002018c0?)
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/cmd/commands/cli/command.go:86 +0xa0
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2.(*Command).Run(0x4000162900, 0x4000218fc0)
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2/command.go:163 +0x50c
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2.(*App).RunContext(0x4000583a00, {0x1af6e58?, 0x4000144020}, {0x400012c000, 0x2, 0x2})
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2/app.go:313 +0x898
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2.(*App).Run(...)
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2/app.go:224
main.main()
	/build/myst-c3SwiB/myst-1.9.2+build570175622+focal/go/src/github.com/mysteriumnetwork/node/cmd/mysterium_node/mysterium_node.go:66 +0xb4

```

**Comment by tomasmik** [comment]
thanks for reporting, we'll look into it.

**Comment by tomasmik** [comment]
Resolved.

**Comment by n10ty** [comment]
Will be fixed in next release

**Comment by blackmennewstyle** [comment]
Dang, you guys are fast :O
Have a great week <3
