### ISSUE TITLE
Panic on autoreconnect

### ISSUE THREAD

**Issue by n10ty** [mysteriumnetwork/node#5421]
```go
2022-09-08T18:36:02.492 DBG ../../eventbus/event_bus.go:101                > Published topic="Trace" event={ID:6ccfba6c-a78b-41fe-8e64-69901011d5de Key:Consumer session creation Duration:1.047050058s}
2022-09-08T18:36:02.492 DBG ../../eventbus/event_bus.go:101                > Published topic="Trace" event={ID:6ccfba6c-a78b-41fe-8e64-69901011d5de Key:Consumer session creation (start) Duration:1.765191ms}
2022-09-08T18:36:02.493 DBG ../../eventbus/event_bus.go:101                > Published topic="Trace" event={ID:6ccfba6c-a78b-41fe-8e64-69901011d5de Key:Consumer start connection Duration:1.069226ms}
2022-09-08T18:36:02.493 DBG ../../core/connection/manager.go:306           > Consumer connection trace: "Consumer whole autoReconnect" took 7.950972805s, "Consumer P2P channel creation" took 6.595532727s, "Consumer P2P connect" took 1.771320867s, "Consumer P2P exchange" took 4.201281873s, "Consumer P2P exchange (ports)" took 2.464862ms, "Consumer P2P exchange ack" took 310.563505ms, "Consumer P2P dial (pinger)" took 188.460533ms, "Consumer P2P dial ack" took 1.191544ms, "Consumer session creation" took 1.047050058s, "Consumer session creation (start)" took 1.765191ms, "Consumer start connection" took 1.069226ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x106cdb2]

goroutine 68732 [running]:
github.com/mysteriumnetwork/node/services/wireguard/connection.(*Connection).restartConn(0x1?, {{0x1c54520, 0x0}, {{0xc000dfc140, 0x10, 0x10}, {0xc000dfc12c, 0x4, 0x4}}, {0xc00023ee70, ...}, ...})
	/go/src/github.com/mysteriumnetwork/node/services/wireguard/connection/connection.go:197 +0x72
github.com/mysteriumnetwork/node/services/wireguard/connection.(*Connection).start(_, {_, _}, _, {{{0xc000237860, 0x2a}}, {{0x0, {0xc0002394d0, 0x13}, 0x2, ...}, ...}, ...})
	/go/src/github.com/mysteriumnetwork/node/services/wireguard/connection/connection.go:147 +0x435
github.com/mysteriumnetwork/node/services/wireguard/connection.(*Connection).Reconnect(_, {_, _}, {{{0xc000237860, 0x2a}}, {{0x0, {0xc0002394d0, 0x13}, 0x2, {0xc0005c02d0, ...}, ...}, ...}, ...})
	/go/src/github.com/mysteriumnetwork/node/services/wireguard/connection/connection.go:109 +0x85
github.com/mysteriumnetwork/node/core/connection.(*connectionManager).startConnection(_, {_, _}, {_, _}, _, {{{0xc000237860, 0x2a}}, {{0x0, {0xc0002394d0, ...}, ...}, ...}, ...}, ...)
	/go/src/github.com/mysteriumnetwork/node/core/connection/manager.go:677 +0x148
github.com/mysteriumnetwork/node/core/connection.(*connectionManager).autoReconnect(0xc0001d0a00)
	/go/src/github.com/mysteriumnetwork/node/core/connection/manager.go:321 +0x41d
github.com/mysteriumnetwork/node/core/connection.(*connectionManager).reconnectOnHold(_, {{0x1525694, 0x6}, {{0xc0be9201b7dc76bd, 0xf0a2c891, 0x25fd340}, {{0xc0011f0090, 0x2a}}, {{0xc0005da4c0, 0xb}, ...}, ...}})
	/go/src/github.com/mysteriumnetwork/node/core/connection/manager.go:892 +0x11b
reflect.Value.call({0x12c1a60?, 0xc000816890?, 0x13?}, {0x15233ac, 0x4}, {0xc000a4a720, 0x1, 0x1?})
	/usr/local/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x12c1a60?, 0xc000816890?, 0xc000f76200?}, {0xc000a4a720, 0x1, 0x1})
	/usr/local/go/src/reflect/value.go:339 +0xbf
github.com/mysteriumnetwork/EventBus.(*EventBus).doPublish(0xc0002ae360, 0xc00114a930, {0x15244a6, 0x5}, {0xc000f76200?, 0xc000ec8400?, 0x46a2ae?})
	/go/pkg/mod/github.com/mysteriumnetwork/!event!bus@v0.0.0-20220415063055-d22cb121672c/event_bus.go:155 +0xf6
github.com/mysteriumnetwork/EventBus.(*EventBus).doPublishAsync(0xc000819b30?, 0x442c45?, {0x15244a6?, 0xc000982fd0?}, {0xc000f76200?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/mysteriumnetwork/!event!bus@v0.0.0-20220415063055-d22cb121672c/event_bus.go:177 +0xa5
created by github.com/mysteriumnetwork/EventBus.(*EventBus).Publish
	/go/pkg/mod/github.com/mysteriumnetwork/!event!bus@v0.0.0-20220415063055-d22cb121672c/event_bus.go:147 +0x232
```

**Comment by n10ty** [comment]
Docker 

Mysterium Node
  Version: 1.14.0
  Build info: Branch: 1.14.0. Build id: 634429363. Commit: b3b211c7
