### ISSUE TITLE
Panic on out of memory

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#5427]
relates to #5409
logs: https://github.com/mysteriumnetwork/node/issues/5409#issuecomment-1245326376
user claims nothing running on rpi except myst node
```
Sep 13 10:09:08 raspberry-myst myst[6380]: runtime: out of memory: cannot allocate 507510784-byte block (1106345984 in use)
Sep 13 10:09:08 raspberry-myst myst[6380]: fatal error: out of memory
Sep 13 10:09:08 raspberry-myst myst[6380]: goroutine 2183 [running]:
Sep 13 10:09:08 raspberry-myst myst[6380]: runtime.throw({0x101f0e7, 0xd})
Sep 13 10:09:08 raspberry-myst myst[6380]:         /usr/lib/go-1.18/src/runtime/panic.go:992 +0x5c fp=0x38690e0 sp=0x38690cc pc=0x4d928
Sep 13 10:09:08 raspberry-myst myst[6380]: runtime.(*mcache).allocLarge(0x76d412e0, 0x1e1f8000, 0x0)
Sep 13 10:09:08 raspberry-myst myst[6380]:         /usr/lib/go-1.18/src/runtime/mcache.go:215 +0x1e8 fp=0x3869108 sp=0x38690e0 pc=0x2931c
Sep 13 10:09:08 raspberry-myst myst[6380]: runtime.mallocgc(0x1e1f8000, 0xf3a210, 0x1)
Sep 13 10:09:08 raspberry-myst myst[6380]:         /usr/lib/go-1.18/src/runtime/malloc.go:1096 +0x6b0 fp=0x3869148 sp=0x3869108 pc=0x1ef3c
Sep 13 10:09:08 raspberry-myst myst[6380]: runtime.growslice(0xf3a210, {0x23800000, 0x2021800, 0x2021800}, 0x2021801)
Sep 13 10:09:08 raspberry-myst myst[6380]:         /usr/lib/go-1.18/src/runtime/slice.go:278 +0x498 fp=0x3869170 sp=0x3869148 pc=0x68a7c
Sep 13 10:09:08 raspberry-myst myst[6380]: github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*Cursor).first(0x3869238)
Sep 13 10:09:08 raspberry-myst myst[6380]:         /build/myst-cIEVt6/myst-1.14.0+build634429363+focal/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/cursor.go:182 +0x120 fp=0x38691a0 sp=0x3869170 pc=0x844650
Sep 13 10:09:08 raspberry-myst myst[6380]: github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*Cursor).next(0x3869238)
Sep 13 10:09:08 raspberry-myst myst[6380]:         /build/myst-cIEVt6/myst-1.14.0+build634429363+focal/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/cursor.go:234 +0x54 fp=0x38691c4 sp=0x38691a0 pc=0x8449a0
Sep 13 10:09:08 raspberry-myst myst[6380]: github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*Cursor).Next(0x3869238)
Sep 13 10:09:08 raspberry-myst myst[6380]:         /build/myst-cIEVt6/myst-1.14.0+build634429363+focal/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/cursor.go:75 +0x30 fp=0x3869208 sp=0x38691c4 pc=0x843eb0
Sep 13 10:09:08 raspberry-myst myst[6380]: github.com/mysteriumnetwork/node/vendor/github.com/asdine/storm/v3/index.(*UniqueIndex).RemoveID(0x36089e8, {0x3bf0480, 0x26, 0x30})
Sep 13 10:09:08 raspberry-myst myst[6380]:         /build/myst-cIEVt6/myst-1.14.0+build634429363+focal/go/src/github.com/mysteriumnetwork/node/vendor/github.com/asdine/storm/v3/index/unique.go:65 +0xa8 fp=0x3869248 sp=0x3869208 pc=0x858c44
```

**Comment by ZygintasBudrys** [comment]
No more complains, very hard to reproduce, rarely occuring
