### ISSUE TITLE
After updating the node, it is a sudden stop and error

### ISSUE THREAD

**Issue by bagyanugraha** [mysteriumnetwork/node#6007]
**Describe the bug**
after updating the node, it is a sudden stop and error

**Environment (please complete the following information):**
 - Node version:1.29.9
 - OS: Ubuntu 22.04.3

Started Server for Mysterium - decentralised VPN Network.
2024-03-06T15:43:50.582 DBG config/config.go:81                      > Loading user configuration: /etc/mysterium-node/config-mainnet.toml
2024-03-06T15:43:50.583 INF config/config.go:93                      > User configuration loaded:
{"active-services":"scraping,data_transfer,dvpn","ether":{"client":{"rpcl2":["https://polygon1.mysterium.network/","https://polygon-rpc.com/"]}},"mmn":{"api-key":"v8W3gdJbWoLN2UuThY8T0dmS3R92XDFfq2YfriQn"},"node":{"version":"1173225955"},"shaper":{"bandwidth":3750,"enabled":true},"stun-servers":["stun.l.google.com:19302","stun1.l.google.com:19302","stun2.l.google.com:19302"],"terms":{"consumer-agreed":true,"provider-agreed":true,"version":"0.0.53"},"udp":{"ports":"4222:4999"}}
2024-03-06T15:43:50.604 DBG config/config.go:221                     > Returning user config value ether.client.rpcl2:[https://polygon1.mysterium.network/ https://polygon-rpc.com/]
2024-03-06T15:43:50.604 DBG config/config.go:216                     > Returning CLI value data-dir:/var/lib/mysterium-node
2024-03-06T15:43:50.604 DBG config/config.go:216                     > Returning CLI value data-dir:/var/lib/mysterium-node
2024-03-06T15:43:50.604 DBG config/config.go:216                     > Returning CLI value script-dir:/etc/mysterium-node
2024-03-06T15:43:50.604 DBG config/config.go:216                     > Returning CLI value runtime-dir:/var/run/mysterium-node
2024-03-06T15:43:50.604 DBG config/config.go:216                     > Returning CLI value keystore.lightweight:true
2024-03-06T15:43:50.605 INF logconfig/config.go:74                   > Log level: debug
2024-03-06T15:43:50.605 INF logconfig/config.go:76                   > Log file path: /var/lib/mysterium-node/.mysterium/logs/mysterium-node
2024-03-06T15:43:50.605 DBG logconfig/rollingwriter/rollingwriter.go:80 > Found 5 old log files in log directory, skipping cleanup
2024-03-06T15:43:50.605 INF cmd/di.go:223                            > Starting Mysterium Node 1.29.9
2024-03-06T15:43:50.606 INF firewall/incoming_firewall_noop.go:32    > Rules bootstrap was requested
2024-03-06T15:43:50.606 INF firewall/incoming_firewall_noop.go:38    > Rules reset was requested
2024-03-06T15:43:50.606 INF firewall/outgoing_firewall_noop.go:35    > Rules reset was requested
panic: invalid freelist page: 125, page type is leaf
goroutine 1 [running]:
github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*freelist).read(0x0?, 0x7fc54d22b000)
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/freelist.go:266 +0x22e
github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*DB).loadFreelist.func1()
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/db.go:316 +0xb8
sync.(*Once).doSlow(0xc000ad61c0?, 0x10?)
        /usr/lib/go-1.20/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/lib/go-1.20/src/sync/once.go:65
github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*DB).loadFreelist(0xc000ad6000?)
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/db.go:309 +0x47
github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.Open({0xc000ab94a0, 0x2a}, 0x1?, 0xc0005505a0)
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/db.go:286 +0x48b
github.com/mysteriumnetwork/node/vendor/github.com/asdine/storm/v3.Open({0xc000ab94a0, 0x2a}, {0x0, 0x0, 0x2a?})
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/github.com/asdine/storm/v3/storm.go:59 +0x28e
github.com/mysteriumnetwork/node/core/storage/boltdb.openDB({0xc000ab94a0?, 0x0?})
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/core/storage/boltdb/storage.go:41 +0x29
github.com/mysteriumnetwork/node/core/storage/boltdb.NewStorage({0xc000ab89c0?, 0x30?})
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/core/storage/boltdb/storage.go:36 +0x5b
github.com/mysteriumnetwork/node/cmd.(*Dependencies).bootstrapStorage(0xc000567080, {0xc000ab89c0?, 0xc000ab89c0?})
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/cmd/di.go:495 +0x45
github.com/mysteriumnetwork/node/cmd.(*Dependencies).Bootstrap(_, {{{0x7ffe6e6add2a, 0x17}, {0xc000ab89c0, 0x22}, {0xc000aa7840, 0x20}, {0x7ffe6e6add0b, 0x13}, {0x7ffe6e6add50, ...}, ...}, ...})
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/cmd/di.go:241 +0x2da
github.com/mysteriumnetwork/node/cmd/commands/service.NewCommand.func1(0xc000927600)
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/cmd/commands/service/command.go:66 +0x155
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2.(*Command).Run(0xc000542f20, 0xc000927600, {0xc000975aa0, 0x2, 0x2})
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2/command.go:274 +0x9eb
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2.(*Command).Run(0xc00091c6e0, 0xc000525400, {0xc000124000, 0x9, 0x9})
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2/command.go:267 +0xc4d
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2.(*App).RunContext(0xc00091e000, {0x2545b08?, 0xc000130020}, {0xc000124000, 0x9, 0x9})
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2/app.go:332 +0x616
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2.(*App).Run(...)
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/v2/app.go:309
main.main()
        /build/myst-t6ZqMf/myst-1.29.9+build8049389424+jammy/go/src/github.com/mysteriumnetwork/node/cmd/mysterium_node/mysterium_node.go:66 +0xb2
mysterium-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
mysterium-node.service: Failed with result 'exit-code'.
^C

![myst-1-29-9-error](https://github.com/mysteriumnetwork/node/assets/40296360/2fb78dd5-ff9a-40ff-8f29-2c56bac8cad3)

**Comment by neyinkafasi** [comment]
Hi,

I had this too.

Removing myst.db in data/mainnet folder solved it for me.
