### ISSUE TITLE
Data races #3

### ISSUE THREAD

**Issue by Zensey** [mysteriumnetwork/node#6067]
Follow up to https://github.com/mysteriumnetwork/node/issues/5999

**Describe the bug**
A few data races have been found

[race_2.txt](https://github.com/user-attachments/files/16359902/race_2.txt)
[dump_1.txt](https://github.com/user-attachments/files/16359796/dump_1.txt)

**Environment (please complete the following information):**
 - Node version: 1.29.22

**Comment by Zensey** [comment]
Looks like it was fixed in https://github.com/google/gvisor/releases/tag/release-20240115.0

**Comment by Zensey** [comment]
Still happens on node version 1.31.3

```
fatal error: concurrent map iteration and map write

goroutine 32481232 [running]:
gvisor.dev/gvisor/pkg/tcpip/network/internal/ip.(*GenericMulticastProtocolState).SendQueuedReportsLocked(0xc00127a750)
        /go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/pkg/tcpip/network/internal/ip/generic_multicast_protocol.go:490 +0x6e
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*igmpState).sendQueuedReports(...)
        /go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/pkg/tcpip/network/ipv4/igmp.go:601
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).sendQueuedReports(...)
        /go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/pkg/tcpip/network/ipv4/ipv4.go:1370
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).AddAndAcquirePermanentAddress(0xc00127a000, {{{0x22, 0xa0, 0x6f, 0x91, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...}, ...)
        /go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/pkg/tcpip/network/ipv4/ipv4.go:1360 +0x1a6
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).addAddress(0x1?, {0x800, {{{0x22, 0xa0, 0x6f, 0x91, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...}}, ...)
        /go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/pkg/tcpip/stack/nic.go:517 +0x104
gvisor.dev/gvisor/pkg/tcpip/stack.(*Stack).AddProtocolAddress(0xc002d96800, 0x0?, {0x800, {{{0x22, 0xa0, 0x6f, 0x91, 0x0, 0x0, 0x0, ...}, ...}, ...}}, ...)
        /go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/pkg/tcpip/stack/stack.go:1111 +0x135
github.com/mysteriumnetwork/node/services/wireguard/endpoint/netstack-provider.(*netTun).addAddress(0x10?, {{0x22, 0xa0, 0x6f, 0x91, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
        /source/services/wireguard/endpoint/netstack-provider/netstack.go:218 +0x145
github.com/mysteriumnetwork/node/services/wireguard/endpoint/netstack-provider.(*netTun).acceptTCP(0xc0035e7d00, 0xc0032e0e80)
        /source/services/wireguard/endpoint/netstack-provider/netstack.go:237 +0x125
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
        /go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/pkg/tcpip/transport/tcp/forwarder.go:98 +0x313

```
