### ISSUE TITLE
tequila client connect error handling

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#795]
There's an issue with the way tequila client handles connection error handling. It will panic if there's an issue with the connection endpoint. For example, if the connection endpoint times out, we'll get a panic. When a timeout happens, the put call returns an error and a nil response. The response is the n passed to `parseResponseJSON` which will then try and deserialize the body.

culprit line: https://github.com/mysteriumnetwork/node/blob/master/tequilapi/client/client.go#L107

example logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4645fb6]

goroutine 1 [running]:
github.com/mysteriumnetwork/node/tequilapi/client.parseResponseJSON(0x0, 0x46d2980, 0xc0002a82c0, 0x479f1c0, 0xc000101c80)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/tequilapi/client/http_client.go:145 +0x26
github.com/mysteriumnetwork/node/tequilapi/client.(*Client).Connect(0xc000244560, 0xc00032a238, 0x2a, 0xc00032a263, 0x2a, 0xc00032a28e, 0x7, 0x0, 0x46e95c0, 0xc0002b9280, ...)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/tequilapi/client/client.go:107 +0x20c
github.com/mysteriumnetwork/node/cmd/commands/cli.(*cliApp).connect(0xc000101a80, 0xc00032a238, 0x5d)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/cmd/commands/cli/command.go:305 +0x28a
github.com/mysteriumnetwork/node/cmd/commands/cli.(*cliApp).handleActions(0xc000101a80, 0xc00032a230, 0x65)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/cmd/commands/cli/command.go:169 +0x471
github.com/mysteriumnetwork/node/cmd/commands/cli.(*cliApp).Run(0xc000101a80, 0x4a5ec98, 0xc000254180)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/cmd/commands/cli/command.go:118 +0x397
github.com/mysteriumnetwork/node/cmd/commands/cli.NewCommand.func1(0xc0001546e0, 0x0, 0xc0001546e0)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/cmd/commands/cli/command.go:66 +0x1dd
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli.HandleAction(0x46fe740, 0x4a5ea88, 0xc0001546e0, 0xc0000d2c00, 0x0)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli.Command.Run(0x480d7f5, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4828a23, 0x24, 0x0, ...)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/command.go:210 +0x92f
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli.(*App).Run(0xc0000fe820, 0xc0000d4000, 0x2, 0x2, 0x0, 0x0)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/app.go:255 +0x69b
main.main()
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/cmd/mysterium_node/mysterium_node.go:54 +0xcd
```

**Comment by chompomonim** [comment]
@vkuznecovas is this still relevant?

**Comment by chompomonim** [comment]
Closing as no activity for a long time and this issue is not relevant anymore.
