### ISSUE TITLE
Service crashes after 6th client connected (panic: runtime error: index out of range)

### ISSUE THREAD

**Issue by Germuxas** [mysteriumnetwork/node#814]
```
C:\Program Files\MysteriumVPN\bin> .\myst.exe --testnet service openvpn --agreed-terms-and-conditions
2019-03-21T15:45:46.0825054 [Info] Starting Mysterium Node (0.0.0-dev)
2019-03-21T15:45:46.1005195 [Info] [Openvpn check] OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on May 15 2018
2019-03-21T15:45:46.1005195 [Info] [Openvpn check] library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
2019-03-21T15:45:46.1005195 [Info] [Openvpn check] Windows version 6.2 (Windows 8 or greater) 64bit
2019-03-21T15:45:46.1005195 [Info] [Openvpn check] Originally developed by James Yonan
2019-03-21T15:45:46.1005195 [Info] [Openvpn check] Copyright (C) 2002-2018 OpenVPN Inc <sales@openvpn.net>
2019-03-21T15:45:46.1005195 [Info] [Openvpn check] Custom tag: Compile time defines: enable_async_push=no enable_comp_stub=no enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=no enable_def_auth=yes enable_dependency_tracking=no enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_iproute2=no enable_libtool_lock=yes enable_lz4=yes enable_lzo=yes enable_management=yes enable_multihome=yes enable_pam_dlopen=no enable_pedantic=no enable_pf=yes enable_pkcs11=yes enable_plugin_auth_pam=no enable_plugin_down_root=no enable_plugins=no enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=no enable_shared_with_static_runtimes=yes enable_silent_rules=no enable_small=no enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=no enable_werror=no enable_win32_dll=yes enable_x509_alt_username=no with_aix_soname=aix with_crypto_library=openssl with_gnu_ld=yes with_mem_check=no with_special_build=standalone-2.4.6-2-62 with_sysroot=no
...
...


panic: runtime error: index out of range

goroutine 148 [running]:
github.com/mysteriumnetwork/node/session.(*StorageMemory).Find(0xc0002ad200, 0xc00001afd5, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000ad3200)
        /ext-go/1/src/github.com/mysteriumnetwork/node/session/storage_memory.go:65 +0x172
github.com/mysteriumnetwork/node/services/openvpn/session.(*clientMap).FindClientSession(0xc000b88040, 0x6, 0xc00001afd5, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5, ...)
        /ext-go/1/src/github.com/mysteriumnetwork/node/services/openvpn/session/client_map.go:44 +0x9e
github.com/mysteriumnetwork/node/services/openvpn/session.(*Validator).Validate(0xc000b88020, 0x6, 0xc00001afd5, 0x24, 0xc0002c6a95, 0x58, 0x3, 0xf72860, 0xc000b2f8c0)
        /ext-go/1/src/github.com/mysteriumnetwork/node/services/openvpn/session/validator.go:52 +0x90
github.com/mysteriumnetwork/node/services/openvpn/session.(*Validator).Validate-fm(0x6, 0xc00001afd5, 0x24, 0xc0002c6a95, 0x58, 0x90000000064f298, 0x40d479, 0x0)
        /ext-go/1/src/github.com/mysteriumnetwork/node/services/openvpn/service/factory.go:83 +0x63
github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/middlewares/server/auth.(*middleware).authenticateClient(0xc000ab9590, 0x6, 0x2, 0xc00001afd5, 0x24, 0xc0002c6a95, 0x58, 0x6, 0x0)
        /ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/middlewares/server/auth/middleware.go:177 +0x265
github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/middlewares/server/auth.(*middleware).handleClientEvent(0xc000ab9590, 0xc00001ce28, 0x6, 0x6, 0x2, 0xc000142780)
        /ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/middlewares/server/auth/middleware.go:156 +0x141
github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/middlewares/server/auth.(*middleware).endOfEvent(0xc000ab9590)
        /ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/middlewares/server/auth/middleware.go:143 +0x51
github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/middlewares/server/auth.(*middleware).ConsumeLine(0xc000ab9590, 0xc000ade020, 0xf, 0xc000b731b0, 0x0, 0x0)
        /ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/middlewares/server/auth/middleware.go:108 +0x5a8
github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/management.(*Management).deliverOpenvpnManagementEvents(0xc0001bebd0, 0xc000052420)
        /ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/management/listener.go:226 +0x323
github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/management.(*Management).serveNewConnection.func2(0xc00014e010, 0xc0001bebd0, 0xc000052420)
        /ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/management/listener.go:167 +0x62
created by github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/management.(*Management).serveNewConnection
        /ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/mysteriumnetwork/go-openvpn/openvpn/management/listener.go:165 +0x2ea
```

**Comment by vkuznecovas** [comment]
Test to reproduce
```golang
func TestStorage_Remove_Panics(t *testing.T) {
	storage := mockStorage(sessionExisting)
	sessionFirst := Session{ID: ID("id4")}
	sessionSecond := Session{ID: ID("id3")}
	storage.Add(sessionFirst)
	storage.Add(sessionSecond)
	storage.Remove(ID("id4"))
	storage.Remove(ID("id3"))
	assert.Len(t, storage.sessions, 0)
	assert.Len(t, storage.idToIndex, 0)
}
```
