### ISSUE TITLE
Bounty Tester: Can't Start the Service (Win10)

### ISSUE THREAD

**Issue by AndriusMyst** [mysteriumnetwork/node#956]
**Problem:**
Cannot start the service
`2019-04-30T11:46:04.554Z info: TequilapiError: Request failed with status code 404 (path="services/9acdf042-aed4-41d6-a230-90238ceee48d")`

**User**:
Location: GB
Telegram: `@Sovietsquirrel`

**Node Client**
Build version: 0.8.0(2251)-0.7.0
ID: 0x57daba353514f004c86edf2e3892740ec4d98c4d

**Hardware**
Win10, server2016
Router- "Pfsense", Vodafone - 40mbps

**LOGS**:

```
2019-04-30T11:50:27.863Z info: "[MysteriumVpn] Application launch"
2019-04-30T11:50:27.867Z info: "[MysteriumVpn] Checking terms cache"
2019-04-30T11:50:27.899Z info: "[MysteriumVpn] Opening window"
2019-04-30T11:50:27.914Z info: "[MysteriumVpn] Waiting for renderer boot"
2019-04-30T11:50:29.266Z info: "[MysteriumVpn] Renderer booted"
2019-04-30T11:50:29.267Z info: "[MysteriumVpn] Building tray"
2019-04-30T11:50:29.299Z info: "[needs-install] checksum mismatch"
2019-04-30T11:50:29.300Z info: "[ProcessManager] Installing 'mysterium_client' process"
2019-04-30T11:50:29.301Z info: "[install] config needs to be recreated"
2019-04-30T11:50:29.261Z info: "Renderer was mounted, will initialize"
2019-04-30T11:50:29.267Z info: "Renderer initialized"
2019-04-30T11:50:29.507Z info: "user exec" "sc.exe query \"MysteriumClient\"" "SERVICE_NAME: MysteriumClient \r\n        TYPE               : 10  WIN32_OWN_PROCESS  \r\n        STATE              : 4  RUNNING \r\n                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)\r\n        WIN32_EXIT_CODE    : 0  (0x0)\r\n        SERVICE_EXIT_CODE  : 0  (0x0)\r\n        CHECKPOINT         : 0x0\r\n        WAIT_HINT          : 0x0"
2019-04-30T11:50:29.559Z info: "user exec" "\"C:\\Program Files\\MysteriumVPN\\bin\\openvpn.exe\" --show-adapters" "Available TAP-WIN32 adapters [name, GUID]:\r\n'Ethernet 3' {33774587-840D-43FB-B2A7-E574610110DD}"
2019-04-30T11:50:29.562Z info: "[ProcessManager] Starting 'mysterium_client' process"
2019-04-30T11:50:29.605Z info: "user exec" "sc.exe query \"MysteriumClient\"" "SERVICE_NAME: MysteriumClient \r\n        TYPE               : 10  WIN32_OWN_PROCESS  \r\n        STATE              : 4  RUNNING \r\n                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)\r\n        WIN32_EXIT_CODE    : 0  (0x0)\r\n        SERVICE_EXIT_CODE  : 0  (0x0)\r\n        CHECKPOINT         : 0x0\r\n        WAIT_HINT          : 0x0"
2019-04-30T11:50:29.630Z info: "[ProcessManager] 'mysterium_client' started successful"
2019-04-30T11:50:29.630Z info: "[ProcessManager] Starting 'mysterium_client' monitoring"
2019-04-30T11:50:29.631Z info: "[ProcessManager] Waiting for process to check version"
2019-04-30T11:50:29.638Z info: "[ProcessManager] Checking client version"
2019-04-30T11:50:29.642Z info: "[VersionCheck] Installed: 0.7.0, running: 0.7.0"
2019-04-30T11:50:29.645Z info: "Route changes / -> /load"
2019-04-30T11:50:29.642Z info: "[ProcessManager] 'mysterium_client' installed version matches running version"
2019-04-30T11:50:29.642Z info: "[ProcessManager] 'mysterium_client' is up"
2019-04-30T11:50:29.643Z info: "[MysteriumVpn] Starting proposal fetcher"
2019-04-30T11:50:31.223Z info: "Registration fetcher started with ID 0x57daba353514f004c86edf2e3892740ec4d98c4d"
2019-04-30T11:50:31.238Z info: "Route changes /load -> /vpn"
2019-04-30T11:50:31.457Z info: "Identity registration fetched" {"registered":true,"publicKey":{"part1":"0xc90a648807568b52d64be011058626ebf03c8361e343db2b063eccad33f9e775","part2":"0xf9b8d6af85f68943eb6c6617b34994bdfd596c6ea7c1b5319b8016ce79ddbfc8"},"signature":{"r":"0x0925fc74bb28a3f17c809e10559507769bdc6b6e7aaf8bc631e4319efaced283","s":"0x733ad4c1daecb3e7a9867c6e940410f8b3924395e30cad6ccfe332e36b64d9e3","v":27}}
2019-04-30T11:50:35.344Z info: "Route changes /vpn -> /provider"
2019-04-30T11:50:36.234Z info: "Identity registration fetched" {"registered":true,"publicKey":{"part1":"0xc90a648807568b52d64be011058626ebf03c8361e343db2b063eccad33f9e775","part2":"0xf9b8d6af85f68943eb6c6617b34994bdfd596c6ea7c1b5319b8016ce79ddbfc8"},"signature":{"r":"0x0925fc74bb28a3f17c809e10559507769bdc6b6e7aaf8bc631e4319efaced283","s":"0x733ad4c1daecb3e7a9867c6e940410f8b3924395e30cad6ccfe332e36b64d9e3","v":27}}
2019-04-30T11:50:41.043Z error: "Unknown status value: STARTING"
2019-04-30T11:50:41.044Z info: "Capturing bug reporter message (level: error): Unknown status value: STARTING"
2019-04-30T11:50:41.269Z info: "Identity registration fetched" {"registered":true,"publicKey":{"part1":"0xc90a648807568b52d64be011058626ebf03c8361e343db2b063eccad33f9e7
```

from stderr

[stdout.txt](https://github.com/mysteriumnetwork/mysterium-vpn/files/3131095/stdout.txt)

```
2019/04/30 11:25:22 bolt.Close(): funlock error: The segment is already unlocked.
failed to open boltDB: timeout
2019-04-30T11:25:26.994523 [service] Post http://127.0.0.1:4050/stop: dial tcp 127.0.0.1:4050: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by Germuxas** [comment]
ps script from node for debugging
```powershell
regsvr32 /s hnetcfg.dll;
$iface = Get-WmiObject Win32_NetworkAdapter | Where-Object {$_.ServiceName -eq "tap0901"} | foreach { $_.NetConnectionID }
echo 'iface:' $iface
$netShare = New-Object -ComObject HNetCfg.HNetShare;
$c = $netShare.EnumEveryConnection |? { $netshare.NetConnectionProps.Invoke($_).Name -eq "$iface" };
$config = $netShare.INetSharingConfigurationForINetConnection.Invoke($c); $config.EnableSharing(1);
echo 'config:' $config
$guid = $netShare.NetConnectionProps.Invoke($c).Guid;
echo 'guid:' $guid
$props = Get-WmiObject -Class HNet_ConnectionProperties -Namespace "ROOT\microsoft\homenet" -Filter "__PATH like '%$guid%'";$props.IsIcsPublic = 0;$props.IsIcsPrivate = 1; $props.Put();
```

**Comment by sovietSquirrel** [comment]
Is it by coincidence I've been tagged in this for some reason?

**Comment by Germuxas** [comment]
Yeah we might have duplicated some emails, as we have to scrape the list manually, so as you are already in the bounty program, you can just ignore this email :)

**Comment by tadaskay** [comment]
Yeah, your github handle accidentally matched the telegram handle included in the issue description. Feel free to hit unsubscribe.

**Comment by tadaskay** [comment]
Relevant error from node (provider)

```
2019-05-09T16:02:19.5703577 [Warn] [service bootstrap] Failed to enable NAT forwarding: failed to enable internet connection sharing: 'powershell -Command regsvr32 /s hnetcfg.dll;
		$netShare = New-Object -ComObject HNetCfg.HNetShare;
		$c = $netShare.EnumEveryConnection |? { $netshare.NetConnectionProps.Invoke($_).Name -eq "Ethernet" };
		$config = $netShare.INetSharingConfigurationForINetConnection.Invoke($c);$config.EnableSharing(0)
		$guid = $netShare.NetConnectionProps.Invoke($c).Guid;
		$props = Get-WmiObject -Class HNet_ConnectionProperties -Namespace "ROOT\microsoft\homenet" -Filter "__PATH like '%$guid%'";$props.IsIcsPublic = 1;$props.IsIcsPrivate = 0;$props.Put();': exit status 255 output: 
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at IDispatchInvoke(IntPtr , Int32 , INVOKEKIND , DISPPARAMS& , Variant& , ExcepInfo& , UInt32& )
   at System.Management.Automation.ComInterop.UnsafeMethods.IDispatchInvoke(IntPtr dispatchPointer, Int32 memberDispId, INVOKEKIND flags, DISPPARAMS& dispParams, Variant& result, ExcepInfo& excepInfo, UInt32& argErr)
   at CallSite.Target(Closure , CallSite , ComObject , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by tadaskay** [comment]
Errors from system event log when running similar command via powershell (fails on `.EnableSharing(1)`

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Events><Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Windows Error Reporting'/><EventID Qualifiers='0'>1001</EventID><Level>4</Level><Task>0</Task><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2019-05-09T16:10:25.855854400Z'/><EventRecordID>61589</EventRecordID><Channel>Application</Channel><Computer>WIN-Q3KNCVM7F60</Computer><Security/></System><EventData><Data>1956835154083497343</Data><Data>4</Data><Data>APPCRASH</Data><Data>Not available</Data><Data>0</Data><Data>PowerShell_ISE.exe</Data><Data>10.0.14393.103</Data><Data>57b7d8fb</Data><Data>hnetcfgclient.dll</Data><Data>10.0.14393.2608</Data><Data>5bd13530</Data><Data>c0000005</Data><Data>0000000000016038</Data><Data></Data><Data></Data><Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD83.tmp.WERInternalMetadata.xml</Data><Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_PowerShell_ISE.e_db62f87d77b6cf72c8b0335140cfc21de74953b7_9d159ca8_0c4a67a9</Data><Data></Data><Data>0</Data><Data>08c52cb3-d9d5-4ef5-afe5-14939e355d03</Data><Data>0</Data><Data>72120da33e6a44823b2813347324c57f</Data></EventData></Event><Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Application Error'/><EventID Qualifiers='0'>1000</EventID><Level>2</Level><Task>100</Task><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2019-05-09T16:10:01.845966800Z'/><EventRecordID>61588</EventRecordID><Channel>Application</Channel><Computer>WIN-Q3KNCVM7F60</Computer><Security/></System><EventData><Data>PowerShell_ISE.exe</Data><Data>10.0.14393.103</Data><Data>57b7d8fb</Data><Data>hnetcfgclient.dll</Data><Data>10.0.14393.2608</Data><Data>5bd13530</Data><Data>c0000005</Data><Data>0000000000016038</Data><Data>42c</Data><Data>01d506819d91c0ab</Data><Data>C:\Windows\system32\WindowsPowerShell\v1.0\PowerShell_ISE.exe</Data><Data>C:\Windows\system32\hnetcfgclient.dll</Data><Data>08c52cb3-d9d5-4ef5-afe5-14939e355d03</Data><Data></Data><Data></Data></EventData></Event><Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='.NET Runtime'/><EventID Qualifiers='0'>1026</EventID><Level>2</Level><Task>0</Task><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2019-05-09T16:10:01.568965900Z'/><EventRecordID>61587</EventRecordID><Channel>Application</Channel><Computer>WIN-Q3KNCVM7F60</Computer><Security/></System><EventData><Data>Application: PowerShell_ISE.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at DynamicClass.IDispatchInvoke(IntPtr, Int32, System.Runtime.InteropServices.ComTypes.INVOKEKIND, System.Runtime.InteropServices.ComTypes.DISPPARAMS ByRef, System.Management.Automation.ComInterop.Variant ByRef, System.Management.Automation.ComInterop.ExcepInfo ByRef, UInt32 ByRef)
   at System.Management.Automation.ComInterop.UnsafeMethods.IDispatchInvoke(IntPtr, Int32, System.Runtime.InteropServices.ComTypes.INVOKEKIND, System.Runtime.InteropServices.ComTypes.DISPPARAMS ByRef, System.Management.Automation.ComInterop.Variant ByRef, System.Management.Automation.ComInterop.ExcepInfo ByRef, UInt32 ByRef)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Management.Automation.ComInterop.ComObject, Int32)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, Int32)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, Int32)
   at System.Management.Automation.Interpreter.DynamicInstruction`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1&lt;System.Management.Automation.Language.FunctionContext&gt;, System.Object, System.Object)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data></EventData></Event></Events>


- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"> 
- <System> 
<Provider Name=".NET Runtime" /> 
<EventID Qualifiers="0">1026</EventID> 
<Level>2</Level> 
<Task>0</Task> 
<Keywords>0x80000000000000</Keywords> 
<TimeCreated SystemTime="2019-05-09T16:10:01.568965900Z" /> 
<EventRecordID>61587</EventRecordID> 
<Channel>Application</Channel> 
<Computer>WIN-Q3KNCVM7F60</Computer> 
<Security /> 
</System> 
- <EventData> 
<Data>Application: PowerShell_ISE.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at DynamicClass.IDispatchInvoke(IntPtr, Int32, System.Runtime.InteropServices.ComTypes.INVOKEKIND, System.Runtime.InteropServices.ComTypes.DISPPARAMS ByRef, System.Management.Automation.ComInterop.Variant ByRef, System.Management.Automation.ComInterop.ExcepInfo ByRef, UInt32 ByRef) at System.Management.Automation.ComInterop.UnsafeMethods.IDispatchInvoke(IntPtr, Int32, System.Runtime.InteropServices.ComTypes.INVOKEKIND, System.Runtime.InteropServices.ComTypes.DISPPARAMS ByRef, System.Management.Automation.ComInterop.Variant ByRef, System.Management.Automation.ComInterop.ExcepInfo ByRef, UInt32 ByRef) at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Management.Automation.ComInterop.ComObject, Int32) at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, Int32) at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, Int32) at System.Management.Automation.Interpreter.DynamicInstruction`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.Management.Automation.Interpreter.InterpretedFrame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame) at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon) at System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object) at System.Management.Automation.DlrScriptCommandProcessor.Complete() at System.Management.Automation.CommandProcessorBase.DoComplete() at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase) at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object) at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper() at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc() at System.Management.Automation.Runspaces.PipelineThread.WorkerProc() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()</Data> 
</EventData> 
</Event>


- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"> 
- <System> 
<Provider Name="Application Error" /> 
<EventID Qualifiers="0">1000</EventID> 
<Level>2</Level> 
<Task>100</Task> 
<Keywords>0x80000000000000</Keywords> 
<TimeCreated SystemTime="2019-05-09T16:10:01.845966800Z" /> 
<EventRecordID>61588</EventRecordID> 
<Channel>Application</Channel> 
<Computer>WIN-Q3KNCVM7F60</Computer> 
<Security /> 
</System> 
- <EventData> 
<Data>PowerShell_ISE.exe</Data> 
<Data>10.0.14393.103</Data> 
<Data>57b7d8fb</Data> 
<Data>hnetcfgclient.dll</Data> 
<Data>10.0.14393.2608</Data> 
<Data>5bd13530</Data> 
<Data>c0000005</Data> 
<Data>0000000000016038</Data> 
<Data>42c</Data> 
<Data>01d506819d91c0ab</Data> 
<Data>C:\Windows\system32\WindowsPowerShell\v1.0\PowerShell_ISE.exe</Data> 
<Data>C:\Windows\system32\hnetcfgclient.dll</Data> 
<Data>08c52cb3-d9d5-4ef5-afe5-14939e355d03</Data> 
<Data /> 
<Data /> 
</EventData> 
</Event>
```

**Comment by tadaskay** [comment]
Updated PS script with fallover to manual connection property patch:

```powershell
regsvr32 /s hnetcfg.dll

function GetInterfaceName() {
  Get-WmiObject -Query "SELECT NetConnectionId FROM win32_networkadapter WHERE ServiceName = 'tap0901'" | foreach { $_.NetConnectionId }
}

function GetNetworkConnectionManager() {
  New-Object -ComObject HNetCfg.HNetShare
}

function FindConnectionForInterface() {
  $mgr = $args[0]
  $interface = $args[1]
  $mgr.EnumEveryConnection |? { $mgr.NetConnectionProps.Invoke($_).Name -eq "$interface" }
}

function GetConnectionProps() {
  $mgr = $args[0]
  $conn = $args[1]
  $guid = $mgr.NetConnectionProps.Invoke($conn).Guid
  Get-WmiObject -Namespace "root\microsoft\homenet" -Query "SELECT * FROM HNet_ConnectionProperties WHERE __PATH LIKE '%$guid%'"
}

function ManuallyPatchConnectionProps() {
  $props = $args[0]
  $props.IsIcsPublic = 0
  $props.IsIcsPrivate = 1
  $props.Put()
}

Write-Output "== Finding private interface (tap0901)"
$interface = GetInterfaceName
Write-Output "== Found private interface:";
Write-Output $interface

$mgr = GetNetworkConnectionManager
$conn = FindConnectionForInterface $mgr $interface
$conn_config = $mgr.INetSharingConfigurationForINetConnection($conn)

Write-Output "== Connection props"
GetConnectionProps $mgr $conn

Write-Output "== Enabling ICS"

Try {
  $conn_config.EnableSharing(1)
  Write-Output "EnableSharing() success"
} Catch {
  $err = $_.Exception.Message
  $log = "Error occurred in .EnableSharing(): $err"; Write-Output $log

  Write-Output "Manually patching connection props"
  $props = GetConnectionProps $mgr $conn
  ManuallyPatchConnectionProps $props

  $conn_config.EnableSharing(1)
  Write-Output "EnableSharing() success after patch"
}

Write-Output "== Connection props"
GetConnectionProps $mgr $conn 

Write-Output "DONE"
```

**Comment by tadaskay** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/ics-internet-connection-sharing-dosent-work-in/a203c90f-1214-4e5e-ae90-9832ae5ceb55?page=1

**Comment by tadaskay** [comment]
Appears to be a windows ICS issue. Works in windows 10 after the latest update. However, still persists on Windows server 2016. In fact, it's not possible to enable sharing using windows UI itself:

![Screenshot 2019-05-10 at 11 39 56](https://user-images.githubusercontent.com/4745368/57514115-63115380-7318-11e9-9869-7800a6b58ab5.png)

![Screenshot 2019-05-10 at 11 39 45](https://user-images.githubusercontent.com/4745368/57514111-60166300-7318-11e9-9860-ae6984d5a443.png)
